# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# https://www.ianwootten.co.uk/2020/10/23/publishing-to-pypi-using-github-actions/
name: Publish nuts to PyPI and release on GitHub
on:
  push:
    tags:
      - "*"

jobs:
  build-and-publish-to-pypi:
    name: Build and publish nuts to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Configure API token
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"
      - name: Build and then publish nuts to PyPI
        run: poetry publish --build
  relase-on-github:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release on Github
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/release_notes/${{ github.ref_name }}.md
