name: Publish nuts to PyPI and release on GitHub
on:
  push:
    tags:
      - "*"

jobs:
  build-and-publish-to-pypi:
    name: Build and publish nuts to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.13"

      - name: build release
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  relase-on-github:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Release on Github
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/release_notes/${{ github.ref_name }}.md
